name: autopep8_check

on: [push, pull_request]

jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Check code formatting
      run: |
        autopep8 --diff --ignore=E501 hw2_rsc/*.py > post_traces/autopep8_trace.txt
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: post_traces/autopep8_trace.txt
