name: Bandit Security Check

on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit
      run: |
        bandit -r hw2_rsc/rand.py -f txt -o post_traces/bandit_trace.txt
