name: Create Badge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: e08fb0f4d4d2ebffe6c63b3be6f0b21d  # Replace with your actual Gist ID
          filename: test.json  # Use test.svg if you want to use the SVG mode
          label: Hello
          message: World
          color: orange

      - name: Commit Badge
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add test.json  # Update to your actual badge file name
          git commit -m "Update badge" || echo "No changes to commit"
          git push
