name: Pyflakes

on:
  push:
    branches: [main]  # Change to your branch if needed
  pull_request:
    branches: [main]

jobs:
  pyflakes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify the Python version you use

      - name: Install Pyflakes
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes

      - name: Run Pyflakes
        id: pyflakes
        run: |
          pyflakes ./hw2_rsc/*.py > pyflakes-report.txt
          if [ -s pyflakes-report.txt ]; then
            echo "status=fail" >> $GITHUB_ENV
          else
            echo "status=pass" >> $GITHUB_ENV
          fi
        continue-on-error: true

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
            auth: ${{ secrets.GIST_SECRET }}
            gistID: f4ff7b311132c5719ea23ca6dd96d660
            filename: pyflake.json # Use test.svg if you want to use the SVG mode.
            label: Pyflakes
            message: ${{ env.status == 'pass' && 'Pass' || 'Fail' }}
            color: ${{ env.status == 'pass' && 'brightgreen' || 'red' }}
            namedLogo: snowflake
            logoColor: "#ffffff"
