name: Pyflakes

on: [push, pull_request]

jobs:
  pyflakes:
    runs-on: ubuntu-latest
      
    steps:        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify the Python version you use

      - name: Install Pyflakes
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes
              
      - name: Run Pyflakes
        id: pyflakes
        run: |
          mkdir -p post_traces
          pyflakes ./hw2_rsc/*.py | tee ./post_traces/pyflakes_trace.txt
          if [ -s ./post_traces/pyflakes_trace.txt ]; then
            echo "status=fail" >> $GITHUB_ENV
          else
            echo "status=pass" >> $GITHUB_ENV
          fi
        continue-on-error: true
        
      - name: Commit files # commit the output folder
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9
      - run: |
          echo "I am protected!"
          sleep 5
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git pull --rebase
          git add ./post_traces/pyflakes_trace.txt
          git commit --allow-empty -m "Update pyflakes report"
          git push
        
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
            auth: ${{ secrets.GIST_SECRET }}
            gistID: e08fb0f4d4d2ebffe6c63b3be6f0b21d
            filename: test.json # Use test.svg if you want to use the SVG mode.
            label: Pyflakes
            message: ${{ env.status == 'pass' && 'Pass' || 'Fail' }}
            color: ${{ env.status == 'pass' && 'brightgreen' || 'red' }}
            namedLogo: snowflake
            logoColor: "#ffffff"
