name: Pylint Badge

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint jq

      - name: Run Pylint
        id: pylint
        run: |
          pylint_score=$(pylint hw2_src/*.py --exit-zero --output-format=json | jq -r '.[0].score')
          echo "pylint_score=$pylint_score" >> $GITHUB_ENV

      - name: Create Badges Directory
        run: |
          mkdir -p ./badges

      - name: Generate Badge
        run: |
          score=$(echo ${{ env.pylint_score }} | awk '{printf("%.1f\n", $1)}')
          color=$(if (( $(echo "$score >= 8" | bc -l) )); then echo "brightgreen"; elif (( $(echo "$score >= 6" | bc -l) )); then echo "yellow"; else echo "red"; fi)
          badge_url="https://img.shields.io/badge/Pylint-$score-$color.svg"
          curl -o ./badges/pylint-score.svg $badge_url

      - name: Commit Badge
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add ./badges/pylint-score.svg
          git commit -m "Update Pylint badge" || echo "No changes to commit"
          git push
