name: Pylint Badge

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        id: pylint
        run: |
          pylint_score=$(pylint hw2_src/*.py --exit-zero --score=y --output-format=json | jq -r '.[0].score')
          echo "Pylint score: $pylint_score"
          echo "badge-score=$pylint_score" >> $GITHUB_ENV

      - name: Generate Badge
        uses: schneegans/dynamic-badges-action@v1
        with:
          label: 'Pylint Score'
          value: ${{ env.badge-score }}
          status: ${{ env.badge-score }}
          color: ${{ steps.pylint.outputs.score >= 8 && 'brightgreen' || steps.pylint.outputs.score >= 6 && 'yellow' || 'red' }}
          filepath: './badges/pylint-score.svg'

      - name: Commit Badge
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add ./badges/pylint-score.svg
          git commit -m "Update Pylint badge" || echo "No changes to commit"
          git push
