name: Lint Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pylint jq

      - name: Run Pylint
        run: |
          pylint ./hw2_rsc/*.py --output-format=json > pylint-report.json || { echo 'Pylint failed'; exit 1; }
          
        continue-on-error: true

      - name: Generate Pylint badge
        id: pylint_badge
        run: |
          # Extract the score from the Pylint report
          pylint_score=$(jq '.[0].score' pylint-report.json)
          
          # Format the score as a percentage
          score_percentage=$(echo "scale=2; $pylint_score * 100" | bc)
          
          # Generate the badge URL with the score
          badge_url="https://img.shields.io/badge/pylint-${score_percentage}%25-brightgreen"
          
          # Output the badge URL as an environment variable
          echo "badge_url=${badge_url}" >> $GITHUB_ENV

