name: Lint Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pylint jq

      - name: Run Pylint
        run: |
          pylint ./hw2_src/*.py --output-format=json > pylint-report.json
          dir
        continue-on-error: true

      - name: Generate Pylint badge
        id: pylint_badge
        run: |
          # Extract the score from the Pylint report
          pylint_score=$(jq '.[0].score' pylint-report.json)
          
          # Format the score as a percentage
          score_percentage=$(echo "scale=2; $pylint_score * 100" | bc)
          
          # Generate the badge URL with the score
          badge_url="https://img.shields.io/badge/pylint-${score_percentage}%25-brightgreen"
          
          # Output the badge URL as an environment variable
          echo "badge_url=${badge_url}" >> $GITHUB_ENV

      - name: Update badge in README
        run: |
          # Download the README.md file
          curl -O https://raw.githubusercontent.com/${{ github.repository }}/main/README.md
          
          # Replace or add badge URL in README.md
          sed -i "s|https://img.shields.io/badge/pylint=.*|${badge_url}|g" README.md
          if ! grep -q "https://img.shields.io/badge/pylint=" README.md; then
            echo "![Pylint Badge](${badge_url})" >> README.md
          fi

          # Commit and push the changes to the repository
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update Pylint badge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
