name: Pylint

on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
      
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: "Setup installation requirements"
        run: |
          pip install --upgrade pip
          pip install pylint

      
      - name: "Lint package(s)"
        run: |
          mkdir -p post_traces
          pylint --exit-zero ./hw2_rsc/*.py | tee ./post_traces/pylint_trace.txt
        
      - name: Commit files # commit the output folder
        uses: ben-z/gh-action-mutex@v1.0.0-alpha.9
        
      - name: Critical Section
        run: |
          sleep 3
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git status
          git add ./post_traces/pylint_trace.txt
          git commit --allow-empty -m "Update pylint report"
          git pull --rebase
          git push
        continue-on-error: true

      - name: Run Pylint & Update Dynamic Badge
        uses: Silleellie/pylint-github-action@v2
        with:
          lint-path: |
            ./hw2_rsc/*.py
          python-version: 3.11
        continue-on-error: true
